SOURCE ./users.sql
SOURCE ./acceptors.sql
SOURCE ./villages.sql
SOURCE ./orders.sql
SOURCE ./pawns.sql
SOURCE ./htet_yus.sql
SOURCE ./pay_interests.sql
SOURCE ./half_redeems.sql
SOURCE ./redeems.sql
SOURCE ./albums.sql
SOURCE ./order_albums.sql